APPLY_FIXES: all
APPLY_FIXES_EVENT: pull_request
APPLY_FIXES_MODE: pull_request
DISABLE_LINTERS:
  - REPOSITORY_GIT_DIFF
ADDITIONAL_EXCLUDED_DIRECTORIES:
  - dev
SPELL_LYCHEE_FILE_EXTENSIONS: "*"
SPELL_CSPELL_ANALYZE_FILE_NAMES: false
MARKDOWN_MARKDOWNLINT_ARGUMENTS: "--ignore tests/testthat/_snaps --ignore LICENSE.md --ignore NEWS.md --ignore README.md --ignore cran-comments.md"
