---
name: MegaLinter
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch: null
  workflow_call: null
permissions: {}
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true
jobs:
  megalinter:
    name: MegaLinter
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout consumer repo
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - name: Checkout r.workflows for linter configs
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          repository: NovoNordisk-OpenSource/r.workflows
          ref: ${{ github.repository == 'NovoNordisk-OpenSource/r.workflows' && (github.head_ref || github.ref_name) || 'main' }}
          path: .r-workflows
          persist-credentials: false
      - name: Setup linter config
        uses: ./.r-workflows/.github/actions/setup-linter-config
      - name: Remove r.workflows checkout
        shell: bash
        run: rm -rf .r-workflows
      - name: MegaLinter
        id: ml
        uses: oxsecurity/megalinter@0e3ce9b9c8c10effb9b269509cc47ca17cae31c7 # v9.5.0
        env:
          VALIDATE_ALL_CODEBASE: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          JAVASCRIPT_STANDARD_FILTER_REGEX_EXCLUDE: ${{ vars.JAVASCRIPT_STANDARD_FILTER_REGEX_EXCLUDE }}
      - name: Archive production artifacts
        if: success() || failure()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: MegaLinter reports
          path: |
            megalinter-reports
            mega-linter.log
