---
name: MegaLinter
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch: null
  workflow_call: null
permissions: {}
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true
jobs:
  megalinter:
    name: MegaLinter
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - name: Copy linting config from r.workflows/main
        shell: bash
        run: | 
          echo ===========
          echo "$GITHUB_REPOSITORY"
          echo "$GITHUB_HEAD_REF"
          echo "$GITHUB_REF_NAME"
          echo ===========
          if [ "$GITHUB_REPOSITORY" = "NovoNordisk-OpenSource/r.workflows" ]; then
            workflow_branch="${GITHUB_HEAD_REF:-$GITHUB_REF_NAME}"
            echo =========
            echo Using "${workflow_branch}"
            echo =========
          else
            workflow_branch="main"
          fi
          if [ ! -e ".mega-linter.yml" ]; then
            echo "==> Adding .mega-linter.yml"
            curl --output .mega-linter.yml "https://raw.githubusercontent.com/NovoNordisk-OpenSource/r.workflows/${workflow_branch}/.github/linters/.mega-linter.yml"
          fi
          if [ ! -e ".lintr" ]; then
            echo "==> Adding .lintr"
            curl --output .lintr "https://raw.githubusercontent.com/NovoNordisk-OpenSource/r.workflows/${workflow_branch}/.github/linters/.lintr"
          fi
          if [ ! -e ".lycheeignore" ]; then
            echo "==> Adding .lycheeignore"
            curl --output .lycheeignore "https://raw.githubusercontent.com/NovoNordisk-OpenSource/r.workflows/${workflow_branch}/.github/linters/.lycheeignore"
          fi
          if [ ! -e ".cspell.json" ]; then
            echo "==> Adding .cspell.json"
            if [ -e "inst/WORDLIST" ]; then
              curl --output .cspell.json "https://raw.githubusercontent.com/NovoNordisk-OpenSource/r.workflows/${workflow_branch}/.github/linters/.cspell-wordlist.json"
            else
              curl --output .cspell.json "https://raw.githubusercontent.com/NovoNordisk-OpenSource/r.workflows/${workflow_branch}/.github/linters/.cspell.json"
            fi
          fi
      - name: MegaLinter
        id: ml
        uses: oxsecurity/megalinter@0e3ce9b9c8c10effb9b269509cc47ca17cae31c7 # v9.5.0
        env:
          VALIDATE_ALL_CODEBASE: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          JAVASCRIPT_STANDARD_FILTER_REGEX_EXCLUDE: ${{ vars.JAVASCRIPT_STANDARD_FILTER_REGEX_EXCLUDE }}
      - name: Archive production artifacts
        if: success() || failure()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: MegaLinter reports
          path: |
            megalinter-reports
            mega-linter.log
