---
name: pkgdown
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  release:
    types:
      - published
  workflow_dispatch:
  workflow_call:
    inputs:
      use_local_setup_action:
        description: Use composite .github/actions/setup/action.yaml to setup package specific needs
        required: false
        type: boolean
        default: false
      generate_token:
        description: Generate token from GitHub app
        required: false
        type: boolean
        default: false
    secrets:
      TOKEN_APP_ID:
        description: ID of the GitHub app used to generate a new token
        required: false
      TOKEN_APP_PRIVATE_KEY:
        description: Private Key for the GitHub app used to generate a new token
        required: false
permissions: {}
jobs:
  pkgdown:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    concurrency:
      group: 'pkgdown-${{ github.event_name != ''pull_request'' || github.run_id }}'
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - name: Generate custom token
        id: generate-token
        if:  ${{ inputs.generate_token }}
        uses: actions/create-github-app-token@fee1f7d63c2ff003460e3d139729b119787bc349 # v2.2.2
        with:
          app-id: ${{ secrets.TOKEN_APP_ID }}
          private-key: ${{ secrets.TOKEN_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
      - name: Package specific setup
        if:  ${{ inputs.use_local_setup_action }}
        uses: ./.github/actions/setup
      - uses: r-lib/actions/setup-pandoc@d3c5be51b12e724e68f33216ca3c148b66d5f0b6 # v2.12.1
      - uses: r-lib/actions/setup-r@d3c5be51b12e724e68f33216ca3c148b66d5f0b6 # v2.12.1
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@d3c5be51b12e724e68f33216ca3c148b66d5f0b6 # v2.12.1
        env:
          GITHUB_PAT: ${{ steps.generate-token.outputs.token || secrets.GITHUB_TOKEN }}
        with:
          extra-packages: 'any::pkgdown, local::.'
          needs: website
      - name: Build site
        run: 'pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)'
        shell: 'Rscript {0}'
      - name: "Deploy to GitHub pages \U0001F680"
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@65b5dfd4f5bcd3a7403bbc2959c144256167464e # v4.5.0
        with:
          clean: false
          branch: gh-pages
          folder: docs
      - name: Add pkgdown PR Comment
        uses: marocchino/sticky-pull-request-comment@773744901bac0e8cbb5a0dc842800d45e9b2b405 # v2.9.4
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          header: pkgdown
          message: >
            # Github pages

            Review the pkgdown webpage for the PR [here](https://${{
            github.repository_owner }}.github.io/${{
            github.event.repository.name }}/dev/${{
            github.event.pull_request.number }})
      - name: Copy page to temp folder
        if: github.event_name == 'pull_request'
        run: |
          mkdir -p /home/runner/work/dev
          cp -r ./docs/* /home/runner/work/dev
      - name: Check out gh-pages branch
        if: github.event_name == 'pull_request'
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          ref: gh-pages
          persist-credentials: false
      - name: Copy and push to gh-pages
        if: github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh auth setup-git
          mkdir -p dev/${{ github.event.pull_request.number }}
          cp -r /home/runner/work/dev/* ./dev/${{ github.event.pull_request.number }}
          git config --global user.email "actions-robot@novonordisk.com"
          git config --global user.name "Actions Robot From Github Actions"
          git add .
          git commit -m "Update gh pages from the PR"
          git push
      - name: Restore original checkout for cleanup
        if: always() && inputs.use_local_setup_action
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          clean: false
          persist-credentials: false
